test:
  aws_access_key_id: AKIAIH73NQHFSUK4ZT6Q
  aws_secret_access_key: us-east-1
  aws_default_region: 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

development:
  aws_access_key_id: AKIAIH73NQHFSUK4ZT6Q
  aws_secret_access_key: us-east-1
  aws_default_region: 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
